sudo: required

services:
    - docker

before_install:
    - docker build -t satishgh12/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run satishgh12/react-test npm test -- --coverage

after_success:
    - docker build -t satishgh12/multiclient ./client
    - docker build -t satishgh12/multinginx ./nginx
    - docker build -t satishgh12/multiserver ./server
    - docker build -t satishgh12/multiworker ./worker

# Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take images and push to docker hub
    - docker push satishgh12/multiclient 
    - docker push satishgh12/multinginx
    - docker push satishgh12/multiserver
    - docker push satishgh12/multiworker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-308347247631
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY